growths:
  ##体型名
  迷你:
    ##实体规模
    scale: 0.5
    ##该体型的稀有值 越小越稀有 0 则无法自然生成出现
    rarity: 5
  侏儒:
    scale: 0.75
    rarity: 10
  娇小:
    scale: 0.9
    rarity: 20
  普通:
    scale: 1.0
    rarity: 30
  高大:
    scale: 1.1
    rarity: 20
  巨人:
    scale: 1.25
    rarity: 10
  庞大:
    scale: 1.5
    rarity: 5
  巨大:
    scale: 1.66
    rarity: 0
  袖珍:
    scale: 0.33
    rarity: 0
  自定义体型(霸王):
    scale: 2.55
    rarity: 0
  自定义体型(最小):
    ##再小下去没办法显示了
    scale: 0.04
    rarity: 0
